# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(852, 715)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.TabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.TabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.TabWidget.setObjectName("TabWidget")
        self.InputTab = QtWidgets.QWidget()
        self.InputTab.setObjectName("InputTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.InputTab)
        self.verticalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.metadataGroup = QtWidgets.QGroupBox(self.InputTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.metadataGroup.sizePolicy().hasHeightForWidth())
        self.metadataGroup.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.metadataGroup.setFont(font)
        self.metadataGroup.setObjectName("metadataGroup")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.metadataGroup)
        self.gridLayout_8.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_8.setSpacing(6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.MDFrame1 = QtWidgets.QFrame(self.metadataGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MDFrame1.sizePolicy().hasHeightForWidth())
        self.MDFrame1.setSizePolicy(sizePolicy)
        self.MDFrame1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MDFrame1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MDFrame1.setObjectName("MDFrame1")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.MDFrame1)
        self.gridLayout_9.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_9.setSpacing(6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.sampleIDLabel = QtWidgets.QLabel(self.MDFrame1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sampleIDLabel.setFont(font)
        self.sampleIDLabel.setObjectName("sampleIDLabel")
        self.gridLayout_9.addWidget(self.sampleIDLabel, 0, 0, 1, 1)
        self.sampleIDText = QtWidgets.QLineEdit(self.MDFrame1)
        self.sampleIDText.setReadOnly(True)
        self.sampleIDText.setClearButtonEnabled(False)
        self.sampleIDText.setObjectName("sampleIDText")
        self.gridLayout_9.addWidget(self.sampleIDText, 0, 1, 1, 1)
        self.sampleDateLabel = QtWidgets.QLabel(self.MDFrame1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sampleDateLabel.setFont(font)
        self.sampleDateLabel.setObjectName("sampleDateLabel")
        self.gridLayout_9.addWidget(self.sampleDateLabel, 1, 0, 1, 1)
        self.sampleDate = QtWidgets.QLineEdit(self.MDFrame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sampleDate.sizePolicy().hasHeightForWidth())
        self.sampleDate.setSizePolicy(sizePolicy)
        self.sampleDate.setReadOnly(True)
        self.sampleDate.setObjectName("sampleDate")
        self.gridLayout_9.addWidget(self.sampleDate, 1, 1, 1, 1)
        self.sampleAcqTimeLabel = QtWidgets.QLabel(self.MDFrame1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sampleAcqTimeLabel.setFont(font)
        self.sampleAcqTimeLabel.setObjectName("sampleAcqTimeLabel")
        self.gridLayout_9.addWidget(self.sampleAcqTimeLabel, 2, 0, 1, 1)
        self.sampleAcqTime = QtWidgets.QLineEdit(self.MDFrame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sampleAcqTime.sizePolicy().hasHeightForWidth())
        self.sampleAcqTime.setSizePolicy(sizePolicy)
        self.sampleAcqTime.setReadOnly(True)
        self.sampleAcqTime.setObjectName("sampleAcqTime")
        self.gridLayout_9.addWidget(self.sampleAcqTime, 2, 1, 1, 1)
        self.sampleDataPointsLabel = QtWidgets.QLabel(self.MDFrame1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sampleDataPointsLabel.setFont(font)
        self.sampleDataPointsLabel.setObjectName("sampleDataPointsLabel")
        self.gridLayout_9.addWidget(self.sampleDataPointsLabel, 3, 0, 1, 1)
        self.sampleDataPoints = QtWidgets.QLineEdit(self.MDFrame1)
        self.sampleDataPoints.setReadOnly(True)
        self.sampleDataPoints.setObjectName("sampleDataPoints")
        self.gridLayout_9.addWidget(self.sampleDataPoints, 3, 1, 1, 1)
        self.gridLayout_8.addWidget(self.MDFrame1, 0, 0, 1, 1)
        self.MDFrame2 = QtWidgets.QFrame(self.metadataGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MDFrame2.sizePolicy().hasHeightForWidth())
        self.MDFrame2.setSizePolicy(sizePolicy)
        self.MDFrame2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MDFrame2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MDFrame2.setObjectName("MDFrame2")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.MDFrame2)
        self.gridLayout_10.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_10.setSpacing(6)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.samplePriIONLabel = QtWidgets.QLabel(self.MDFrame2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.samplePriIONLabel.setFont(font)
        self.samplePriIONLabel.setObjectName("samplePriIONLabel")
        self.gridLayout_10.addWidget(self.samplePriIONLabel, 2, 0, 1, 1)
        self.samplePriIONELabel = QtWidgets.QLabel(self.MDFrame2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.samplePriIONELabel.setFont(font)
        self.samplePriIONELabel.setObjectName("samplePriIONELabel")
        self.gridLayout_10.addWidget(self.samplePriIONELabel, 3, 0, 1, 1)
        self.samplePriIONText = QtWidgets.QLineEdit(self.MDFrame2)
        self.samplePriIONText.setReadOnly(True)
        self.samplePriIONText.setObjectName("samplePriIONText")
        self.gridLayout_10.addWidget(self.samplePriIONText, 2, 2, 1, 1)
        self.speciesListLabel = QtWidgets.QLabel(self.MDFrame2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.speciesListLabel.setFont(font)
        self.speciesListLabel.setObjectName("speciesListLabel")
        self.gridLayout_10.addWidget(self.speciesListLabel, 0, 0, 1, 1)
        self.speciesListText = QtWidgets.QLineEdit(self.MDFrame2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speciesListText.sizePolicy().hasHeightForWidth())
        self.speciesListText.setSizePolicy(sizePolicy)
        self.speciesListText.setReadOnly(True)
        self.speciesListText.setObjectName("speciesListText")
        self.gridLayout_10.addWidget(self.speciesListText, 0, 2, 1, 1)
        self.priIonEValue = QtWidgets.QLineEdit(self.MDFrame2)
        self.priIonEValue.setObjectName("priIonEValue")
        self.gridLayout_10.addWidget(self.priIonEValue, 3, 2, 1, 1)
        self.gridLayout_8.addWidget(self.MDFrame2, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.metadataGroup)
        self.inputInputGroupBox = QtWidgets.QGroupBox(self.InputTab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inputInputGroupBox.setFont(font)
        self.inputInputGroupBox.setObjectName("inputInputGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.inputInputGroupBox)
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.MDInputFrame3 = QtWidgets.QFrame(self.inputInputGroupBox)
        self.MDInputFrame3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MDInputFrame3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MDInputFrame3.setObjectName("MDInputFrame3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.MDInputFrame3)
        self.verticalLayout_3.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.addNotesLabel = QtWidgets.QLabel(self.MDInputFrame3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addNotesLabel.setFont(font)
        self.addNotesLabel.setObjectName("addNotesLabel")
        self.verticalLayout_3.addWidget(self.addNotesLabel)
        self.addNotesText = QtWidgets.QTextEdit(self.MDInputFrame3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addNotesText.sizePolicy().hasHeightForWidth())
        self.addNotesText.setSizePolicy(sizePolicy)
        self.addNotesText.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.addNotesText.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.addNotesText.setObjectName("addNotesText")
        self.verticalLayout_3.addWidget(self.addNotesText)
        self.gridLayout.addWidget(self.MDInputFrame3, 1, 0, 1, 2)
        self.MDInputFrame2 = QtWidgets.QFrame(self.inputInputGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MDInputFrame2.sizePolicy().hasHeightForWidth())
        self.MDInputFrame2.setSizePolicy(sizePolicy)
        self.MDInputFrame2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MDInputFrame2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MDInputFrame2.setObjectName("MDInputFrame2")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.MDInputFrame2)
        self.gridLayout_11.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_11.setSpacing(6)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.matrixCompLabel = QtWidgets.QLabel(self.MDInputFrame2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.matrixCompLabel.setFont(font)
        self.matrixCompLabel.setObjectName("matrixCompLabel")
        self.gridLayout_11.addWidget(self.matrixCompLabel, 0, 0, 1, 1)
        self.matrixCompComboBox = QtWidgets.QComboBox(self.MDInputFrame2)
        self.matrixCompComboBox.setEditable(True)
        self.matrixCompComboBox.setObjectName("matrixCompComboBox")
        self.gridLayout_11.addWidget(self.matrixCompComboBox, 0, 1, 1, 1)
        self.sputtRateLabel = QtWidgets.QLabel(self.MDInputFrame2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sputtRateLabel.setFont(font)
        self.sputtRateLabel.setObjectName("sputtRateLabel")
        self.gridLayout_11.addWidget(self.sputtRateLabel, 1, 0, 1, 1)
        self.inputSputtRate = QtWidgets.QDoubleSpinBox(self.MDInputFrame2)
        self.inputSputtRate.setDecimals(5)
        self.inputSputtRate.setMaximum(2000.0)
        self.inputSputtRate.setObjectName("inputSputtRate")
        self.gridLayout_11.addWidget(self.inputSputtRate, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.MDInputFrame2, 0, 1, 1, 1)
        self.MDInputFrame1 = QtWidgets.QFrame(self.inputInputGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MDInputFrame1.sizePolicy().hasHeightForWidth())
        self.MDInputFrame1.setSizePolicy(sizePolicy)
        self.MDInputFrame1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MDInputFrame1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MDInputFrame1.setObjectName("MDInputFrame1")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.MDInputFrame1)
        self.gridLayout_12.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_12.setSpacing(6)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.inputAnnTemp = QtWidgets.QDoubleSpinBox(self.MDInputFrame1)
        self.inputAnnTemp.setMaximum(2000.0)
        self.inputAnnTemp.setObjectName("inputAnnTemp")
        self.gridLayout_12.addWidget(self.inputAnnTemp, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.MDInputFrame1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_12.addWidget(self.label_2, 2, 0, 1, 1)
        self.inputCoolingMethod = QtWidgets.QComboBox(self.MDInputFrame1)
        self.inputCoolingMethod.setEditable(True)
        self.inputCoolingMethod.setObjectName("inputCoolingMethod")
        self.gridLayout_12.addWidget(self.inputCoolingMethod, 4, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.MDInputFrame1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_12.addWidget(self.label_3, 4, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.MDInputFrame1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_12.addWidget(self.label_7, 0, 0, 1, 1)
        self.inputGasComposition = QtWidgets.QComboBox(self.MDInputFrame1)
        self.inputGasComposition.setEditable(True)
        self.inputGasComposition.setObjectName("inputGasComposition")
        self.gridLayout_12.addWidget(self.inputGasComposition, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.MDInputFrame1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_12.addWidget(self.label_6, 1, 0, 1, 1)
        self.inputAnnTime = QtWidgets.QDoubleSpinBox(self.MDInputFrame1)
        self.inputAnnTime.setMaximum(200.0)
        self.inputAnnTime.setObjectName("inputAnnTime")
        self.gridLayout_12.addWidget(self.inputAnnTime, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.MDInputFrame1, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.inputInputGroupBox)
        self.inputButtonFrame = QtWidgets.QFrame(self.InputTab)
        self.inputButtonFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.inputButtonFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.inputButtonFrame.setObjectName("inputButtonFrame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.inputButtonFrame)
        self.gridLayout_2.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.openDFButton = QtWidgets.QPushButton(self.inputButtonFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openDFButton.sizePolicy().hasHeightForWidth())
        self.openDFButton.setSizePolicy(sizePolicy)
        self.openDFButton.setObjectName("openDFButton")
        self.gridLayout_2.addWidget(self.openDFButton, 0, 0, 1, 1)
        self.saveDataButton = QtWidgets.QPushButton(self.inputButtonFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveDataButton.sizePolicy().hasHeightForWidth())
        self.saveDataButton.setSizePolicy(sizePolicy)
        self.saveDataButton.setObjectName("saveDataButton")
        self.gridLayout_2.addWidget(self.saveDataButton, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.inputButtonFrame)
        self.TabWidget.addTab(self.InputTab, "")
        self.ExtractTab = QtWidgets.QWidget()
        self.ExtractTab.setObjectName("ExtractTab")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.ExtractTab)
        self.gridLayout_7.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_7.setSpacing(6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.extractDataButton = QtWidgets.QPushButton(self.ExtractTab)
        self.extractDataButton.setObjectName("extractDataButton")
        self.gridLayout_7.addWidget(self.extractDataButton, 3, 1, 1, 1)
        self.filtersGroup = QtWidgets.QGroupBox(self.ExtractTab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.filtersGroup.setFont(font)
        self.filtersGroup.setObjectName("filtersGroup")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.filtersGroup)
        self.gridLayout_3.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.filterAnnTempLabel = QtWidgets.QLabel(self.filtersGroup)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.filterAnnTempLabel.setFont(font)
        self.filterAnnTempLabel.setObjectName("filterAnnTempLabel")
        self.gridLayout_3.addWidget(self.filterAnnTempLabel, 0, 1, 1, 1)
        self.filterCoolingLabel = QtWidgets.QLabel(self.filtersGroup)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.filterCoolingLabel.setFont(font)
        self.filterCoolingLabel.setObjectName("filterCoolingLabel")
        self.gridLayout_3.addWidget(self.filterCoolingLabel, 2, 1, 1, 1)
        self.filterMatrixCompLabel = QtWidgets.QLabel(self.filtersGroup)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.filterMatrixCompLabel.setFont(font)
        self.filterMatrixCompLabel.setObjectName("filterMatrixCompLabel")
        self.gridLayout_3.addWidget(self.filterMatrixCompLabel, 4, 0, 1, 1)
        self.filterAnnTempList = QtWidgets.QListWidget(self.filtersGroup)
        self.filterAnnTempList.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.filterAnnTempList.setObjectName("filterAnnTempList")
        self.gridLayout_3.addWidget(self.filterAnnTempList, 1, 1, 1, 1)
        self.filterSpeciesList = QtWidgets.QListWidget(self.filtersGroup)
        self.filterSpeciesList.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.filterSpeciesList.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.filterSpeciesList.setObjectName("filterSpeciesList")
        self.gridLayout_3.addWidget(self.filterSpeciesList, 1, 0, 3, 1)
        self.filterCoolingList = QtWidgets.QListWidget(self.filtersGroup)
        self.filterCoolingList.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.filterCoolingList.setObjectName("filterCoolingList")
        self.gridLayout_3.addWidget(self.filterCoolingList, 3, 1, 1, 1)
        self.filterGasCompList = QtWidgets.QListWidget(self.filtersGroup)
        self.filterGasCompList.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.filterGasCompList.setObjectName("filterGasCompList")
        self.gridLayout_3.addWidget(self.filterGasCompList, 5, 1, 1, 1)
        self.filterMatrixCompList = QtWidgets.QListWidget(self.filtersGroup)
        self.filterMatrixCompList.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.filterMatrixCompList.setObjectName("filterMatrixCompList")
        self.gridLayout_3.addWidget(self.filterMatrixCompList, 5, 0, 1, 1)
        self.filterSpeciesLabel = QtWidgets.QLabel(self.filtersGroup)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.filterSpeciesLabel.setFont(font)
        self.filterSpeciesLabel.setObjectName("filterSpeciesLabel")
        self.gridLayout_3.addWidget(self.filterSpeciesLabel, 0, 0, 1, 1)
        self.filterGasCompLabel = QtWidgets.QLabel(self.filtersGroup)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.filterGasCompLabel.setFont(font)
        self.filterGasCompLabel.setObjectName("filterGasCompLabel")
        self.gridLayout_3.addWidget(self.filterGasCompLabel, 4, 1, 1, 1)
        self.clearButton = QtWidgets.QPushButton(self.filtersGroup)
        self.clearButton.setObjectName("clearButton")
        self.gridLayout_3.addWidget(self.clearButton, 6, 0, 1, 1)
        self.filterButton = QtWidgets.QPushButton(self.filtersGroup)
        self.filterButton.setObjectName("filterButton")
        self.gridLayout_3.addWidget(self.filterButton, 6, 1, 1, 1)
        self.gridLayout_7.addWidget(self.filtersGroup, 0, 1, 1, 1)
        self.samplesGroup = QtWidgets.QGroupBox(self.ExtractTab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.samplesGroup.setFont(font)
        self.samplesGroup.setObjectName("samplesGroup")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.samplesGroup)
        self.gridLayout_6.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_6.setSpacing(6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.samplesList = QtWidgets.QListWidget(self.samplesGroup)
        self.samplesList.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.samplesList.setObjectName("samplesList")
        self.gridLayout_6.addWidget(self.samplesList, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.samplesGroup, 0, 0, 1, 1)
        self.outputSelectionsGroup = QtWidgets.QGroupBox(self.ExtractTab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.outputSelectionsGroup.setFont(font)
        self.outputSelectionsGroup.setObjectName("outputSelectionsGroup")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.outputSelectionsGroup)
        self.gridLayout_5.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.outNormLabel = QtWidgets.QLabel(self.outputSelectionsGroup)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.outNormLabel.setFont(font)
        self.outNormLabel.setObjectName("outNormLabel")
        self.gridLayout_5.addWidget(self.outNormLabel, 0, 0, 1, 1)
        self.outSpeciesLabel = QtWidgets.QLabel(self.outputSelectionsGroup)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.outSpeciesLabel.setFont(font)
        self.outSpeciesLabel.setObjectName("outSpeciesLabel")
        self.gridLayout_5.addWidget(self.outSpeciesLabel, 0, 1, 1, 1)
        self.outNormList = QtWidgets.QListWidget(self.outputSelectionsGroup)
        self.outNormList.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.outNormList.setObjectName("outNormList")
        self.gridLayout_5.addWidget(self.outNormList, 1, 0, 1, 1)
        self.outSpeciesList = QtWidgets.QListWidget(self.outputSelectionsGroup)
        self.outSpeciesList.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.outSpeciesList.setObjectName("outSpeciesList")
        self.gridLayout_5.addWidget(self.outSpeciesList, 1, 1, 1, 1)
        self.gridLayout_7.addWidget(self.outputSelectionsGroup, 1, 0, 2, 2)
        self.TabWidget.addTab(self.ExtractTab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_16.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_16.setSpacing(6)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.metadataGroup_2 = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.metadataGroup_2.sizePolicy().hasHeightForWidth())
        self.metadataGroup_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.metadataGroup_2.setFont(font)
        self.metadataGroup_2.setObjectName("metadataGroup_2")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.metadataGroup_2)
        self.gridLayout_19.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_19.setSpacing(6)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.MDFrame1_2 = QtWidgets.QFrame(self.metadataGroup_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MDFrame1_2.sizePolicy().hasHeightForWidth())
        self.MDFrame1_2.setSizePolicy(sizePolicy)
        self.MDFrame1_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MDFrame1_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MDFrame1_2.setObjectName("MDFrame1_2")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.MDFrame1_2)
        self.gridLayout_14.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_14.setSpacing(6)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.sampleIDLabel_2 = QtWidgets.QLabel(self.MDFrame1_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sampleIDLabel_2.setFont(font)
        self.sampleIDLabel_2.setObjectName("sampleIDLabel_2")
        self.gridLayout_14.addWidget(self.sampleIDLabel_2, 0, 0, 1, 1)
        self.displaySampleID = QtWidgets.QLineEdit(self.MDFrame1_2)
        self.displaySampleID.setReadOnly(True)
        self.displaySampleID.setClearButtonEnabled(False)
        self.displaySampleID.setObjectName("displaySampleID")
        self.gridLayout_14.addWidget(self.displaySampleID, 0, 1, 1, 1)
        self.sampleDateLabel_2 = QtWidgets.QLabel(self.MDFrame1_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sampleDateLabel_2.setFont(font)
        self.sampleDateLabel_2.setObjectName("sampleDateLabel_2")
        self.gridLayout_14.addWidget(self.sampleDateLabel_2, 1, 0, 1, 1)
        self.displayAnalDate = QtWidgets.QLineEdit(self.MDFrame1_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayAnalDate.sizePolicy().hasHeightForWidth())
        self.displayAnalDate.setSizePolicy(sizePolicy)
        self.displayAnalDate.setReadOnly(True)
        self.displayAnalDate.setObjectName("displayAnalDate")
        self.gridLayout_14.addWidget(self.displayAnalDate, 1, 1, 1, 1)
        self.sampleAcqTimeLabel_2 = QtWidgets.QLabel(self.MDFrame1_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sampleAcqTimeLabel_2.setFont(font)
        self.sampleAcqTimeLabel_2.setObjectName("sampleAcqTimeLabel_2")
        self.gridLayout_14.addWidget(self.sampleAcqTimeLabel_2, 2, 0, 1, 1)
        self.displayAcqTime = QtWidgets.QLineEdit(self.MDFrame1_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayAcqTime.sizePolicy().hasHeightForWidth())
        self.displayAcqTime.setSizePolicy(sizePolicy)
        self.displayAcqTime.setReadOnly(True)
        self.displayAcqTime.setObjectName("displayAcqTime")
        self.gridLayout_14.addWidget(self.displayAcqTime, 2, 1, 1, 1)
        self.sampleDataPointsLabel_2 = QtWidgets.QLabel(self.MDFrame1_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sampleDataPointsLabel_2.setFont(font)
        self.sampleDataPointsLabel_2.setObjectName("sampleDataPointsLabel_2")
        self.gridLayout_14.addWidget(self.sampleDataPointsLabel_2, 3, 0, 1, 1)
        self.displayDataPoints = QtWidgets.QLineEdit(self.MDFrame1_2)
        self.displayDataPoints.setReadOnly(True)
        self.displayDataPoints.setObjectName("displayDataPoints")
        self.gridLayout_14.addWidget(self.displayDataPoints, 3, 1, 1, 1)
        self.gridLayout_19.addWidget(self.MDFrame1_2, 0, 0, 1, 1)
        self.MDFrame2_2 = QtWidgets.QFrame(self.metadataGroup_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MDFrame2_2.sizePolicy().hasHeightForWidth())
        self.MDFrame2_2.setSizePolicy(sizePolicy)
        self.MDFrame2_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MDFrame2_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MDFrame2_2.setObjectName("MDFrame2_2")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.MDFrame2_2)
        self.gridLayout_15.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_15.setSpacing(6)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.samplePriIONLabel_2 = QtWidgets.QLabel(self.MDFrame2_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.samplePriIONLabel_2.setFont(font)
        self.samplePriIONLabel_2.setObjectName("samplePriIONLabel_2")
        self.gridLayout_15.addWidget(self.samplePriIONLabel_2, 2, 0, 1, 1)
        self.samplePriIONELabel_2 = QtWidgets.QLabel(self.MDFrame2_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.samplePriIONELabel_2.setFont(font)
        self.samplePriIONELabel_2.setObjectName("samplePriIONELabel_2")
        self.gridLayout_15.addWidget(self.samplePriIONELabel_2, 3, 0, 1, 1)
        self.displayPriIon = QtWidgets.QLineEdit(self.MDFrame2_2)
        self.displayPriIon.setReadOnly(True)
        self.displayPriIon.setObjectName("displayPriIon")
        self.gridLayout_15.addWidget(self.displayPriIon, 2, 2, 1, 1)
        self.speciesListLabel_2 = QtWidgets.QLabel(self.MDFrame2_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.speciesListLabel_2.setFont(font)
        self.speciesListLabel_2.setObjectName("speciesListLabel_2")
        self.gridLayout_15.addWidget(self.speciesListLabel_2, 0, 0, 1, 1)
        self.displaySpeciesList = QtWidgets.QLineEdit(self.MDFrame2_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displaySpeciesList.sizePolicy().hasHeightForWidth())
        self.displaySpeciesList.setSizePolicy(sizePolicy)
        self.displaySpeciesList.setReadOnly(True)
        self.displaySpeciesList.setObjectName("displaySpeciesList")
        self.gridLayout_15.addWidget(self.displaySpeciesList, 0, 2, 1, 1)
        self.displayPriIonE = QtWidgets.QLineEdit(self.MDFrame2_2)
        self.displayPriIonE.setReadOnly(True)
        self.displayPriIonE.setObjectName("displayPriIonE")
        self.gridLayout_15.addWidget(self.displayPriIonE, 3, 2, 1, 1)
        self.gridLayout_19.addWidget(self.MDFrame2_2, 0, 1, 1, 1)
        self.gridLayout_16.addWidget(self.metadataGroup_2, 0, 0, 1, 1)
        self.inputInputGroupBox_2 = QtWidgets.QGroupBox(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inputInputGroupBox_2.setFont(font)
        self.inputInputGroupBox_2.setObjectName("inputInputGroupBox_2")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.inputInputGroupBox_2)
        self.gridLayout_13.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_13.setSpacing(6)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.MDInputFrame2_2 = QtWidgets.QFrame(self.inputInputGroupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MDInputFrame2_2.sizePolicy().hasHeightForWidth())
        self.MDInputFrame2_2.setSizePolicy(sizePolicy)
        self.MDInputFrame2_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MDInputFrame2_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MDInputFrame2_2.setObjectName("MDInputFrame2_2")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.MDInputFrame2_2)
        self.gridLayout_17.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_17.setSpacing(6)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.matrixCompLabel_2 = QtWidgets.QLabel(self.MDInputFrame2_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.matrixCompLabel_2.setFont(font)
        self.matrixCompLabel_2.setObjectName("matrixCompLabel_2")
        self.gridLayout_17.addWidget(self.matrixCompLabel_2, 0, 0, 1, 1)
        self.sputtRateLabel_2 = QtWidgets.QLabel(self.MDInputFrame2_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sputtRateLabel_2.setFont(font)
        self.sputtRateLabel_2.setObjectName("sputtRateLabel_2")
        self.gridLayout_17.addWidget(self.sputtRateLabel_2, 1, 0, 1, 1)
        self.displaySputtRate = QtWidgets.QLineEdit(self.MDInputFrame2_2)
        self.displaySputtRate.setReadOnly(True)
        self.displaySputtRate.setObjectName("displaySputtRate")
        self.gridLayout_17.addWidget(self.displaySputtRate, 1, 1, 1, 1)
        self.displayMatrixComp = QtWidgets.QLineEdit(self.MDInputFrame2_2)
        self.displayMatrixComp.setReadOnly(True)
        self.displayMatrixComp.setObjectName("displayMatrixComp")
        self.gridLayout_17.addWidget(self.displayMatrixComp, 0, 1, 1, 1)
        self.gridLayout_13.addWidget(self.MDInputFrame2_2, 0, 1, 1, 1)
        self.MDInputFrame3_2 = QtWidgets.QFrame(self.inputInputGroupBox_2)
        self.MDInputFrame3_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MDInputFrame3_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MDInputFrame3_2.setObjectName("MDInputFrame3_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.MDInputFrame3_2)
        self.verticalLayout_4.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.addNotesLabel_2 = QtWidgets.QLabel(self.MDInputFrame3_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addNotesLabel_2.setFont(font)
        self.addNotesLabel_2.setObjectName("addNotesLabel_2")
        self.verticalLayout_4.addWidget(self.addNotesLabel_2)
        self.displayAddNotes = QtWidgets.QTextEdit(self.MDInputFrame3_2)
        self.displayAddNotes.setReadOnly(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayAddNotes.sizePolicy().hasHeightForWidth())
        self.displayAddNotes.setSizePolicy(sizePolicy)
        self.displayAddNotes.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.displayAddNotes.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.displayAddNotes.setObjectName("displayAddNotes")
        self.verticalLayout_4.addWidget(self.displayAddNotes)
        self.gridLayout_13.addWidget(self.MDInputFrame3_2, 1, 0, 1, 2)
        self.MDInputFrame1_2 = QtWidgets.QFrame(self.inputInputGroupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MDInputFrame1_2.sizePolicy().hasHeightForWidth())
        self.MDInputFrame1_2.setSizePolicy(sizePolicy)
        self.MDInputFrame1_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MDInputFrame1_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MDInputFrame1_2.setObjectName("MDInputFrame1_2")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.MDInputFrame1_2)
        self.gridLayout_18.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_18.setSpacing(6)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.label_8 = QtWidgets.QLabel(self.MDInputFrame1_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_18.addWidget(self.label_8, 0, 0, 1, 1)
        self.displayAnnTemp = QtWidgets.QLineEdit(self.MDInputFrame1_2)
        self.displayAnnTemp.setReadOnly(True)
        self.displayAnnTemp.setObjectName("displayAnnTemp")
        self.gridLayout_18.addWidget(self.displayAnnTemp, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.MDInputFrame1_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_18.addWidget(self.label_9, 1, 0, 1, 1)
        self.displayAnnTime = QtWidgets.QLineEdit(self.MDInputFrame1_2)
        self.displayAnnTime.setReadOnly(True)
        self.displayAnnTime.setObjectName("displayAnnTime")
        self.gridLayout_18.addWidget(self.displayAnnTime, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.MDInputFrame1_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_18.addWidget(self.label_4, 2, 0, 1, 1)
        self.displayGasComp = QtWidgets.QLineEdit(self.MDInputFrame1_2)
        self.displayGasComp.setReadOnly(True)
        self.displayGasComp.setObjectName("displayGasComp")
        self.gridLayout_18.addWidget(self.displayGasComp, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.MDInputFrame1_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_18.addWidget(self.label_5, 3, 0, 1, 1)
        self.displayCoolMethod = QtWidgets.QLineEdit(self.MDInputFrame1_2)
        self.displayCoolMethod.setReadOnly(True)
        self.displayCoolMethod.setObjectName("displayCoolMethod")
        self.gridLayout_18.addWidget(self.displayCoolMethod, 3, 1, 1, 1)
        self.gridLayout_13.addWidget(self.MDInputFrame1_2, 0, 0, 1, 1)
        self.gridLayout_16.addWidget(self.inputInputGroupBox_2, 1, 0, 1, 1)
        self.TabWidget.addTab(self.tab, "")
        self.gridLayout_4.addWidget(self.TabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 852, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpenFile = QtWidgets.QAction(MainWindow)
        self.actionOpenFile.setObjectName("actionOpenFile")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionOpenFile)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.TabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.sampleIDText, self.sampleDate)
        MainWindow.setTabOrder(self.sampleDate, self.sampleAcqTime)
        MainWindow.setTabOrder(self.sampleAcqTime, self.sampleDataPoints)
        MainWindow.setTabOrder(self.sampleDataPoints, self.speciesListText)
        MainWindow.setTabOrder(self.speciesListText, self.samplePriIONText)
        MainWindow.setTabOrder(self.samplePriIONText, self.inputAnnTemp)
        MainWindow.setTabOrder(self.inputAnnTemp, self.inputGasComposition)
        MainWindow.setTabOrder(self.inputGasComposition, self.inputCoolingMethod)
        MainWindow.setTabOrder(self.inputCoolingMethod, self.matrixCompComboBox)
        MainWindow.setTabOrder(self.matrixCompComboBox, self.addNotesText)
        MainWindow.setTabOrder(self.addNotesText, self.openDFButton)
        MainWindow.setTabOrder(self.openDFButton, self.saveDataButton)
        MainWindow.setTabOrder(self.saveDataButton, self.samplesList)
        MainWindow.setTabOrder(self.samplesList, self.filterSpeciesList)
        MainWindow.setTabOrder(self.filterSpeciesList, self.filterAnnTempList)
        MainWindow.setTabOrder(self.filterAnnTempList, self.filterCoolingList)
        MainWindow.setTabOrder(self.filterCoolingList, self.filterMatrixCompList)
        MainWindow.setTabOrder(self.filterMatrixCompList, self.filterGasCompList)
        MainWindow.setTabOrder(self.filterGasCompList, self.outNormList)
        MainWindow.setTabOrder(self.outNormList, self.outSpeciesList)
        MainWindow.setTabOrder(self.outSpeciesList, self.extractDataButton)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SIMS Data Extractor"))
        self.metadataGroup.setTitle(_translate("MainWindow", "Sample File Information"))
        self.sampleIDLabel.setText(_translate("MainWindow", "Sample ID:"))
        self.sampleDateLabel.setText(_translate("MainWindow", "Date of Analysis:"))
        self.sampleAcqTimeLabel.setText(_translate("MainWindow", "Total Acquisition Time:"))
        self.sampleDataPointsLabel.setText(_translate("MainWindow", "Number of Data Points:"))
        self.samplePriIONLabel.setText(_translate("MainWindow", "Primary Ions:"))
        self.samplePriIONELabel.setText(_translate("MainWindow", "Primary Ions Energy (keV):"))
        self.speciesListLabel.setText(_translate("MainWindow", "Species List:"))
        self.inputInputGroupBox.setTitle(_translate("MainWindow", "Metadata Input"))
        self.addNotesLabel.setText(_translate("MainWindow", "Additional Notes"))
        self.matrixCompLabel.setText(_translate("MainWindow", "Matrix Composition:"))
        self.sputtRateLabel.setText(_translate("MainWindow", "Sputtering Rate (nm/s):"))
        self.label_2.setText(_translate("MainWindow", "Gas Composition:"))
        self.label_3.setText(_translate("MainWindow", "Cooling Method:"))
        self.label_7.setText(_translate("MainWindow", "Annealing Temperature (K):"))
        self.label_6.setText(_translate("MainWindow", "Annealing Time (h):"))
        self.openDFButton.setText(_translate("MainWindow", "OPEN"))
        self.saveDataButton.setText(_translate("MainWindow", "SAVE"))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.InputTab), _translate("MainWindow", "Input Sample Metadata"))
        self.extractDataButton.setText(_translate("MainWindow", "EXTRACT SPECIES DATA TO CSV"))
        self.filtersGroup.setTitle(_translate("MainWindow", "Filter Options"))
        self.filterAnnTempLabel.setText(_translate("MainWindow", "Annealing Temperature (K)"))
        self.filterCoolingLabel.setText(_translate("MainWindow", "Cooling Method"))
        self.filterMatrixCompLabel.setText(_translate("MainWindow", "Matrix Composition"))
        self.filterSpeciesLabel.setText(_translate("MainWindow", "Species"))
        self.filterGasCompLabel.setText(_translate("MainWindow", "Gas Composition"))
        self.clearButton.setText(_translate("MainWindow", "Clear"))
        self.filterButton.setText(_translate("MainWindow", "Filter"))
        self.samplesGroup.setTitle(_translate("MainWindow", "Samples in Database"))
        self.outputSelectionsGroup.setTitle(_translate("MainWindow", "Output Options"))
        self.outNormLabel.setText(_translate("MainWindow", "Species for Normalization Factor"))
        self.outSpeciesLabel.setText(_translate("MainWindow", "Species to Output"))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.ExtractTab), _translate("MainWindow", "Extract Sample Data"))
        self.metadataGroup_2.setTitle(_translate("MainWindow", "Sample File Information"))
        self.sampleIDLabel_2.setText(_translate("MainWindow", "Sample ID:"))
        self.sampleDateLabel_2.setText(_translate("MainWindow", "Date of Analysis:"))
        self.sampleAcqTimeLabel_2.setText(_translate("MainWindow", "Total Acquisition Time:"))
        self.sampleDataPointsLabel_2.setText(_translate("MainWindow", "Number of Data Points:"))
        self.samplePriIONLabel_2.setText(_translate("MainWindow", "Primary Ions:"))
        self.samplePriIONELabel_2.setText(_translate("MainWindow", "Primary Ions Energy (keV):"))
        self.speciesListLabel_2.setText(_translate("MainWindow", "Species List:"))
        self.inputInputGroupBox_2.setTitle(_translate("MainWindow", "Metadata Input"))
        self.matrixCompLabel_2.setText(_translate("MainWindow", "Matrix Composition:"))
        self.sputtRateLabel_2.setText(_translate("MainWindow", "Sputtering Rate (nm/s):"))
        self.addNotesLabel_2.setText(_translate("MainWindow", "Additional Notes"))
        self.label_8.setText(_translate("MainWindow", "Annealing Temperature (K):"))
        self.label_9.setText(_translate("MainWindow", "Annealing Time (h):"))
        self.label_4.setText(_translate("MainWindow", "Gas Composition:"))
        self.label_5.setText(_translate("MainWindow", "Cooling Method:"))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.tab), _translate("MainWindow", "Sample Information"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpenFile.setText(_translate("MainWindow", "Open"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
